TWEAK_NAME = OverlayImage

OverlayImage_FILES = Tweak.xm OverlayManager.m OverlayWindow.m ImagePickerController.m OverlayView.m
OverlayImage_FRAMEWORKS = UIKit QuartzCore Photos
OverlayImage_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
